"""Validated MuJoCo probe primitives and narrow Allegro manipulation paths."""

from allegro_probe.backends import (
    AllegroHandBackend,
    BackendCapabilities,
    FrankaAllegroMujocoBackend,
    ProbeBackend,
    ReferenceProbeBackend,
    UnsupportedPrimitiveError,
    create_backend,
)
from allegro_probe.demo_scenes import make_demo_scene
from allegro_probe.interfaces import ProbeCommand, ProbeHarness
from allegro_probe.geometry import RigidTransform
from allegro_probe.franka_scene import (
    CANONICAL_ALLEGRO_OPEN,
    CANONICAL_PANDA_HOME,
    CANONICAL_Q,
    SYNTHETIC_MOUNT_V1,
    CollisionSnapshot as RobotCollisionSnapshot,
    DistanceAudit,
    FramePose,
    FrankaAllegroScene,
    FrankaSceneConfig,
    ModelProvenance,
    SyntheticMountProfile,
)
from allegro_probe.manipulation import (
    AllegroHandTemplate,
    ManipulationContext,
    ManipulationExecutionResult,
    ManipulationPlan,
    ManipulationPlanDecision,
    ShortCanPickPlaceRequest,
    build_short_can_pick_place_plan,
    execute_short_can_pick_place,
    short_can_hand_template,
)
from allegro_probe.models import ObjectSpec, ProbeResult, ProbeSceneSpec
from allegro_probe.pose_manipulation import (
    POSE_MANIPULATION_SCHEMA_VERSION,
    FixedPlaceSpec,
    GraspCandidate,
    ObjectPoseObservation,
    ObjectRelativeGraspTemplate,
    PoseConditionedPickPlaceRequest,
    PoseConditionedShortCanController,
    build_pose_conditioned_short_can_plan,
    execute_pose_conditioned_short_can_plan,
    generate_short_can_grasp_candidates,
    run_pose_conditioned_short_can_pick_place,
    short_can_top_pinch_template,
)
from allegro_probe.primitives import primitive_for_family, run_probe
from allegro_probe.protocols import (
    EXECUTOR_PROFILE_VERSION,
    FEATURE_SCHEMA_VERSION,
    PROBE_PROTOCOL_ID,
    V1_DEFAULTS,
    ProbeProtocolDefaults,
)
from allegro_probe.scene import AllegroProbeScene, SceneConfig

__all__ = [
    "AllegroProbeScene",
    "AllegroHandBackend",
    "AllegroHandTemplate",
    "BackendCapabilities",
    "CANONICAL_ALLEGRO_OPEN",
    "CANONICAL_PANDA_HOME",
    "CANONICAL_Q",
    "DistanceAudit",
    "FramePose",
    "FrankaAllegroMujocoBackend",
    "FrankaAllegroScene",
    "FrankaSceneConfig",
    "ManipulationContext",
    "ManipulationExecutionResult",
    "ManipulationPlan",
    "ManipulationPlanDecision",
    "ModelProvenance",
    "POSE_MANIPULATION_SCHEMA_VERSION",
    "FEATURE_SCHEMA_VERSION",
    "EXECUTOR_PROFILE_VERSION",
    "FixedPlaceSpec",
    "GraspCandidate",
    "ObjectSpec",
    "ObjectPoseObservation",
    "ObjectRelativeGraspTemplate",
    "ProbeCommand",
    "ProbeHarness",
    "ProbeBackend",
    "ProbeProtocolDefaults",
    "ProbeResult",
    "ProbeSceneSpec",
    "PoseConditionedPickPlaceRequest",
    "PoseConditionedShortCanController",
    "RigidTransform",
    "RobotCollisionSnapshot",
    "SceneConfig",
    "ShortCanPickPlaceRequest",
    "ReferenceProbeBackend",
    "SYNTHETIC_MOUNT_V1",
    "SyntheticMountProfile",
    "UnsupportedPrimitiveError",
    "PROBE_PROTOCOL_ID",
    "V1_DEFAULTS",
    "make_demo_scene",
    "build_short_can_pick_place_plan",
    "create_backend",
    "build_pose_conditioned_short_can_plan",
    "execute_pose_conditioned_short_can_plan",
    "execute_short_can_pick_place",
    "generate_short_can_grasp_candidates",
    "primitive_for_family",
    "run_probe",
    "run_pose_conditioned_short_can_pick_place",
    "short_can_hand_template",
    "short_can_top_pinch_template",
]
